module.exports = function getItems() { return [{id:1, name:'Simple Pistol',qty:1},
  {id:2, name:'Assault Rifle',qty:1},
  {id:3, name:'Rocket Launcher',qty:1},
  {id:4, name:'Simple Bullet',qty:1000},
  {id:5, name:'Bow',qty:1},
  {id:6, name:'Grenade',qty:10},
  {id:7, name:'Wood',qty:1000},
  {id:8, name:'Stone',qty:1000},
  {id:9, name:'Metal',qty:1000},
  {id:10, name:'Hide',qty:1000},
  {id:11, name:'Chitin',qty:1000},
  {id:12, name:'Raw Meat',qty:1000},
  {id:13, name:'Spoiled Meat',qty:1000},
  {id:14, name:'Cooked Meat',qty:1000},
  {id:15, name:'Water Jar',qty:8},
  {id:16, name:'Water Jar (Full)',qty:8},
  {id:17, name:'Cloth Pants',qty:1},
  {id:18, name:'Cloth Shirt',qty:1},
  {id:19, name:'Cloth Hat',qty:1},
  {id:20, name:'Cloth Boots',qty:1},
  {id:21, name:'Cloth Gloves',qty:1},
  {id:22, name:'Hide pants',qty:1},
  {id:23, name:'Hide Shirt',qty:1},
  {id:24, name:'Hide Hat',qty:1},
  {id:25, name:'Hide Boots',qty:1},
  {id:26, name:'Hide Gloves',qty:1},
  {id:27, name:'Chitin Leggings',qty:1},
  {id:28, name:'Chitin Chestpiece',qty:1},
  {id:29, name:'Chitin Helmet',qty:1},
  {id:30, name:'Chitin Boots',qty:1},
  {id:31, name:'Chitin Gauntlets',qty:1},
  {id:32, name:'Stone Arrow',qty:100},
  {id:33, name:'Stone Pick',qty:1},
  {id:34, name:'Stone Hatchet',qty:1},
  {id:35, name:'Metal Pick',qty:1},
  {id:36, name:'Metal Hatchet',qty:1},
  {id:37, name:'Torch',qty:1},
  {id:38, name:'Paintbrush',qty:1},
  {id:39, name:'Campfire',qty:1},
  {id:40, name:'Standing Torch',qty:1},
  {id:41, name:'Hide Sleeping Bag',qty:1},
  {id:42, name:'Remote Detonator',qty:1},
  {id:43, name:'C4 Charge',qty:1},
  {id:44, name:'Blood Extraction Syringe',qty:1},
  {id:45, name:'Blood Pack',qty:1},
  {id:46, name:'Improvised Explosive Device',qty:1},
  {id:47, name:'Waterskin',qty:8},
  {id:48, name:'Waterskin(Full)',qty:8},
  {id:49, name:'Berrybush Seeds',qty:1},
  {id:50, name:'Fertilizer',qty:8},
  {id:51, name:'Bingleberry Soup',qty:1},
  {id:52, name:'Medical Brew (Rockwell)',qty:1},
  {id:53, name:'Energy Brew (Rockwell)',qty:1},
  {id:54, name:'Dinosaur Feces',qty:10},
  {id:55, name:'Human Feces',qty:1},
  {id:56, name:'Stegosaurus Egg',qty:1},
  {id:57, name:'Spear',qty:1},
  {id:58, name:'Red Coloring',qty:1},
  {id:59, name:'Green Coloring',qty:1},
  {id:60, name:'Blue Coloring',qty:1},
  {id:61, name:'Yellow Coloring',qty:1},
  {id:62, name:'Purple Coloring',qty:1},
  {id:63, name:'Orange Coloring',qty:1},
  {id:64, name:'Black Coloring',qty:1},
  {id:65, name:'White Coloring',qty:1},
  {id:66, name:'Brown Coloring',qty:1},
  {id:67, name:'Cyan Coloring',qty:1},
  {id:68, name:'Purple Coloring',qty:1},
  {id:69, name:'Rex Saddle',qty:1},
  {id:70, name:'Tranq Arrow',qty:100},
  {id:71, name:'Pistol Hat Skin',qty:1},
  {id:72, name:'GPS',qty:1},
  {id:73, name:'Flint',qty:1000},
  {id:74, name:'Metal Ingot',qty:1000},
  {id:75, name:'Thatch',qty:1000},
  {id:76, name:'Fiber',qty:1000},
  {id:77, name:'Charcoal',qty:1000},
  {id:78, name:'Crystal',qty:1000},
  {id:79, name:'Thatch Roof',qty:10},
  {id:80, name:'Thatch Door',qty:1},
  {id:81, name:'Thatch Foundation',qty:10},
  {id:82, name:'Thatch Wall',qty:10},
  {id:83, name:'Thatch Doorframe',qty:1},
  {id:84, name:'Wooden Catwalk',qty:10},
  {id:85, name:'Wooden Ceiling',qty:10},
  {id:86, name:'Wooden Hatchframe',qty:1},
  {id:87, name:'Wooden Door',qty:1},
  {id:88, name:'Wooden Foundation',qty:0},
  {id:89, name:'Wooden Ladder',qty:5},
  {id:90, name:'Wooden Pillar',qty:10},
  {id:91, name:'Wooden Ramp',qty:2},
  {id:92, name:'Wooden Trapdoor',qty:1},
  {id:93, name:'Wooden Wall',qty:10},
  {id:94, name:'Wooden Doorframe',qty:1},
  {id:95, name:'Wooden WindowFrame',qty:1},
  {id:96, name:'Wooden Window',qty:1},
  {id:97, name:'Wooden Sign',qty:1},
  {id:98, name:'Note',qty:1},
  {id:99, name:'Citronal',qty:1000},
  {id:100, name:'Parasaur Saddle',qty:1},
  {id:101, name:'Raptor Saddle',qty:1},
  {id:102, name:'Stego Saddle',qty:1},
  {id:103, name:'Trike Saddle',qty:1},
  {id:104, name:'Pulmonoscorpius Saddle',qty:1},
  {id:105, name:'Storage Box',qty:1},
  {id:106, name:'Large Storage Box',qty:1},
  {id:107, name:'Mortar and Pestle',qty:1},
  {id:108, name:'Sparkpowder',qty:1000},
  {id:109, name:'Gunpowder',qty:1000},
  {id:110, name:'Stone Irrigation Pipe - Intake',qty:1},
  {id:111, name:'Stone Irrigation Pipe - Straight',qty:10},
  {id:112, name:'Stone Irrigation Pipe - Incline',qty:10},
  {id:113, name:'Stone Irrigation Pipe - Intersection',qty:10},
  {id:114, name:'Stone Irrigation Pipe - Vertical',qty:10},
  {id:115, name:'Stone Irrigation Pipe - Tap',qty:2},
  {id:116, name:'Amarberry Seed',qty:1},
  {id:117, name:'Amarberry',qty:1000},
  {id:118, name:'Azulberry',qty:1000},
  {id:119, name:'Tintoberry',qty:1000},
  {id:120, name:'Mejoberry',qty:1000},
  {id:121, name:'Narcoberry',qty:1000},
  {id:122, name:'Stimberry',qty:1000},
  {id:123, name:'Narcotic',qty:1000},
  {id:124, name:'Stimulant',qty:1000},
  {id:125, name:'Refining Forge',qty:1},
  {id:126, name:'Smithy',qty:1},
  {id:127, name:'Compost Bin',qty:1},
  {id:128, name:'Cooking Pot',qty:1},
  {id:129, name:'Simple Bed',qty:1},
  {id:130, name:'Small Crop Plot',qty:10},
  {id:131, name:'Pteranodon Saddle',qty:1},
  {id:132, name:'Longneck Rifle',qty:1},
  {id:133, name:'Citronal Seed',qty:1},
  {id:134, name:'Specimen Implant',qty:1},
  {id:135, name:'Bronto Saddle',qty:1},
  {id:136, name:'Wooden Fence Foundation',qty:10},
  {id:137, name:'Compass',qty:1},
  {id:138, name:'Scope Attachment',qty:1},
  {id:139, name:'Slingshot',qty:1},
  {id:140, name:'Pike',qty:1},
  {id:141, name:'Radio',qty:1},
  {id:142, name:'Obsidian',qty:1000},
  {id:143, name:'Dinosaur Gateway',qty:1},
  {id:144, name:'Simple Rifle Ammo',qty:100},
  {id:145, name:'Summon Broodmother',qty:1},
  {id:146, name:'Cementing Paste',qty:1000},
  {id:147, name:'Dinosaur Gate',qty:1},
  {id:148, name:'Artifact of the Hunter',qty:1},
  {id:149, name:'Artifact of the Pack',qty:1},
  {id:150, name:'Artifact of the Massive',qty:1},
  {id:151, name:'Artifact of the Devious',qty:1},
  {id:152, name:'Artifact of the Clever',qty:1},
  {id:153, name:'Artifact of the Skylord',qty:1},
  {id:154, name:'Artifact of the Devourer',qty:1},
  {id:155, name:'Artifact of the Queen',qty:1},
  {id:156, name:'Artifact of the Strong',qty:1},
  {id:157, name:'Artifact of the Flamekeeper',qty:1},
  {id:158, name:'Argentavis Talon (Broodmother)',qty:4},
  {id:159, name:'Megalodon Tooth (Broodmother)',qty:8},
  {id:160, name:'Tyrannosaur Arm (Broodmother)',qty:4},
  {id:161, name:'Saurpod Vertebra (Broodmother)',qty:2},
  {id:162, name:'Oil',qty:1000},
  {id:163, name:'Silica Pearls',qty:1000},
  {id:164, name:'Gasoline',qty:1000},
  {id:165, name:'Electronics',qty:100},
  {id:166, name:'Polymer',qty:1000},
  {id:167, name:'Metal Catwalk',qty:10},
  {id:168, name:'Metal Ceiling',qty:10},
  {id:169, name:'Metal Hatchframe',qty:1},
  {id:170, name:'Metal Door',qty:1},
  {id:171, name:'Metal Fence Foundation',qty:10},
  {id:172, name:'Metal Foundation',qty:10},
  {id:173, name:'Behemoth Gate',qty:1},
  {id:174, name:'Behemoth Gateway',qty:1},
  {id:175, name:'Metal Ladder',qty:10},
  {id:176, name:'Metal Pillar',qty:10},
  {id:177, name:'Metal Ramp',qty:2},
  {id:178, name:'Metal Trapdoor',qty:1},
  {id:179, name:'Metal Wall',qty:10},
  {id:180, name:'Metal Doorframe',qty:1},
  {id:181, name:'Metal Windowframe',qty:1},
  {id:182, name:'metal Window',qty:1},
  {id:183, name:'Super Test meat',qty:100},
  {id:184, name:'Flare Gun',qty:1},
  {id:185, name:'Fabricator',qty:1},
  {id:186, name:'Water Tank',qty:1},
  {id:187, name:'Parachute',qty:1},
  {id:188, name:'Air Conditioner',qty:1},
  {id:189, name:'Electrical Generator',qty:1},
  {id:190, name:'Electrical Outlet',qty:1},
  {id:191, name:'Inclined Electrical Cable',qty:10},
  {id:192, name:'Electrical Cable Intersection',qty:10},
  {id:193, name:'Straight Electrical Cable',qty:10},
  {id:194, name:'Vertical Electrical Cable',qty:10},
  {id:195, name:'Lamppost',qty:5},
  {id:196, name:'Refrigerator',qty:1},
  {id:197, name:'Auto Turret',qty:1},
  {id:198, name:'Remote Keypad',qty:1},
  {id:199, name:'Metal Irrigation Pipe - Inclined',qty:10},
  {id:200, name:'Metal Irrigation Pipe - Intake',qty:1},
  {id:201, name:'Metal Irrigation Pipe - Intersection',qty:5},
  {id:202, name:'Metal Irrigation Pipe - Straight',qty:10},
  {id:203, name:'Metal Irrigation Pipe - Tap',qty:3},
  {id:204, name:'Metal Irrigation Pipe - Vertical',qty:10},
  {id:205, name:'Flashlight Attachment',qty:1},
  {id:206, name:'Silencer Attachment',qty:1},
  {id:207, name:'Carbonemys Saddle',qty:1},
  {id:208, name:'Sarco Saddle',qty:1},
  {id:209, name:'Ankylo Saddle',qty:1},
  {id:210, name:'Mammoth Saddle',qty:1},
  {id:211, name:'Megalodon Saddle',qty:1},
  {id:212, name:'Sabertooth Saddle',qty:1},
  {id:213, name:'Carno Saddle',qty:1},
  {id:214, name:'Argentavis Saddle',qty:1},
  {id:215, name:'Plesiosaur Saddle',qty:1},
  {id:216, name:'Chitin/Keratin',qty:1000},
  {id:217, name:'Keratin',qty:1000},
  {id:218, name:'Metal Sign',qty:1},
  {id:219, name:'Holo-Scope Attachment',qty:1},
  {id:220, name:'Laser Attachment',qty:1},
  {id:221, name:'Wooden Billboard',qty:1},
  {id:222, name:'Flak Leggings',qty:1},
  {id:223, name:'Flak Chestpiece',qty:1},
  {id:224, name:'Flak Helmet',qty:1},
  {id:225, name:'Flak Boots',qty:1},
  {id:226, name:'Flak Gauntlets',qty:1},
  {id:227, name:'Enduro Stew (Rockwell)',qty:1},
  {id:228, name:'Lazarus Chowder (Rockwell)',qty:1},
  {id:229, name:'Calien Soup (Rockwell)',qty:1},
  {id:230, name:'Fria Curry (Rockwell)',qty:1},
  {id:231, name:'Focal Chilli (Rockwell)',qty:1},
  {id:232, name:'Savoroot',qty:1000},
  {id:233, name:'Longgrass',qty:1000},
  {id:234, name:'Rockarrot',qty:1000},
  {id:235, name:'Azulberry Seed',qty:1},
  {id:236, name:'Tintoberry Seed',qty:1},
  {id:237, name:'Mejoberry Seed',qty:1},
  {id:238, name:'Narcoberry Seed',qty:1},
  {id:239, name:'Stimberry Seed',qty:1},
  {id:240, name:'Savoroot Seed',qty:1},
  {id:241, name:'Longgrass Seed',qty:1},
  {id:242, name:'Rockarrot Seed',qty:1},
  {id:243, name:'Metal Billboard',qty:1},
  {id:244, name:'Fabricated Pistol',qty:1},
  {id:245, name:'Advanced Bullet',qty:1000},
  {id:246, name:'Advanced Rifle Bullet',qty:1000},
  {id:247, name:'Rocket Propelled Grenade',qty:100},
  {id:248, name:'Medium Crop Plot',qty:8},
  {id:249, name:'Large Crop Plot',qty:8},
  {id:250, name:'Rare Flower',qty:1000},
  {id:251, name:'Rare Mushroom',qty:1000},
  {id:252, name:'Raw Prime Meat',qty:1000},
  {id:253, name:'Cooked Prime Meat',qty:1000},
  {id:254, name:'Battle Tartare (Rockwell)',qty:1},
  {id:255, name:'Shadow Steak Saute (Rockwell)',qty:1},
  {id:256, name:'Rockwell Recipes: Enduro Stew',qty:1},
  {id:257, name:'Rockwell Recipes: Lazarus Chowder',qty:1},
  {id:258, name:'Rockwell Recipes: Calien Soup',qty:1},
  {id:259, name:'Rockwell Recipes: Fria Curry',qty:1},
  {id:260, name:'Rockwell Recipes: Focal Chilli',qty:1},
  {id:261, name:'Rockwell Recipes: Battle Tartare',qty:1},
  {id:262, name:'Rockwell Recipes: Shadow Steak Saute',qty:1},
  {id:263, name:'Notes on Rockwell Recipes',qty:1},
  {id:264, name:'Wall Sign',qty:1},
  {id:265, name:'Metal Dinosaur Gateway',qty:1},
  {id:266, name:'Metal Dinosaur Gate',qty:1},
  {id:267, name:'Shotgun',qty:1},
  {id:268, name:'Simple Shotgun Ammo',qty:100},
  {id:269, name:'Metal Wall Sign',qty:1},
  {id:270, name:'Amarberry Seed',qty:1},
  {id:271, name:'Azulberry Seed',qty:1},
  {id:272, name:'Tintoberry Seed',qty:1},
  {id:273, name:'Narcoberry Seed',qty:1},
  {id:274, name:'Stimberry Seed',qty:1},
  {id:275, name:'Mejoberry Seed',qty:1},
  {id:276, name:'Citronal Seed',qty:1},
  {id:277, name:'Savaroot Seed',qty:1},
  {id:278, name:'Longgrass Seed',qty:1},
  {id:279, name:'Rockarrot Seed',qty:1},
  {id:280, name:'Flag',qty:1},
  {id:281, name:'Hunter Skin Hat',qty:1},
  {id:282, name:'Rex Stomped Glasses Saddle',qty:1},
  {id:283, name:'Spyglass',qty:1},
  {id:284, name:'Spider Flag',qty:1},
  {id:285, name:'Phiomia Saddle',qty:1},
  {id:286, name:'Medium Dinosaur Feces',qty:1},
  {id:287, name:'Large Dinosaur Feces',qty:10},
  {id:288, name:'Brontosaurus Egg',qty:1},
  {id:289, name:'Parasaur Egg',qty:1},
  {id:290, name:'Raptor Egg',qty:1},
  {id:291, name:'T-Rex Egg',qty:1},
  {id:292, name:'Triceratops Egg',qty:1},
  {id:293, name:'Parasaur ARK Founder Saddle Skin',qty:1},
  {id:294, name:'Dodo Egg',qty:1},
  {id:295, name:'Preserving Bin',qty:1},
  {id:296, name:'Metal Spike Wall',qty:1},
  {id:297, name:'Cooked Meat Jerky (Rockwell)',qty:1000},
  {id:298, name:'Prime Meat Jerky (Rockwell)',qty:1000},
  {id:299, name:'Rex Bone Helmet Skin',qty:1},
  {id:300, name:'Nerdry Glasses Skin',qty:1},
  {id:301, name:'Rockwell Recipes: Medical Brew',qty:1},
  {id:302, name:'Rockwell Recipes: Energy Brew',qty:1},
  {id:303, name:'Spinosaur Saddle',qty:1},
  {id:304, name:'Rockwell Recipes: Meat Jerky',qty:1},
  {id:305, name:'Heavy Miners Helmet',qty:1},
  {id:306, name:'Steel Vault',qty:1},
  {id:307, name:'Wood Spike Wall',qty:10},
  {id:308, name:'Dino Glasses',qty:1},
  {id:309, name:'Bookshelf',qty:1},
  {id:310, name:'Stone Fence Foundation',qty:10},
  {id:311, name:'Stone Wall',qty:10},
  {id:312, name:'Metal Water Reservoir',qty:1},
  {id:313, name:'Plesiosaur Saddle',qty:1},
  {id:314, name:'Ichthyosaur Saddle',qty:1},
  {id:315, name:'Stone Ceiling',qty:10},
  {id:316, name:'Stone Hatchframe',qty:1},
  {id:317, name:'Reinforced Wooden Door',qty:1},
  {id:318, name:'Stone Foundation',qty:10},
  {id:319, name:'Reinforced Dinosaur Gate',qty:1},
  {id:320, name:'Stone Dinosaur Gateway',qty:1},
  {id:321, name:'Stone Pillar',qty:10},
  {id:322, name:'Stone Doorframe',qty:1},
  {id:323, name:'Stone Windowframe',qty:1},
  {id:324, name:'Fireworks Flaregun Skin',qty:1},
  {id:325, name:'Tripwire Narcotic Trap',qty:2},
  {id:326, name:'Tripwire Alarm Trap',qty:2},
  {id:327, name:'Kibble (Ankylo Egg)',qty:100},
  {id:328, name:'Kibble (Argentavis Egg)',qty:100},
  {id:329, name:'Kibble (Titanaboa Egg)',qty:100},
  {id:330, name:'Kibble (Carno Egg)',qty:100},
  {id:331, name:'Kibble (Dilo Egg)',qty:100},
  {id:332, name:'Kibble (Dodo Egg)',qty:100},
  {id:333, name:'Kibble (Parasaur Egg)',qty:100},
  {id:334, name:'Kibble (Pteranadon Egg)',qty:100},
  {id:335, name:'Kibble (Raptor Egg)',qty:100},
  {id:336, name:'Kibble (Rex Egg)',qty:100},
  {id:337, name:'Kibble (Sarco Egg)',qty:100},
  {id:338, name:'Kibble (Bronto Egg)',qty:100},
  {id:339, name:'Kibble (Pulminoscorpius Egg)',qty:100},
  {id:340, name:'Kibble (Araneo Egg)',qty:100},
  {id:341, name:'Kibble (Spino Egg)',qty:100},
  {id:342, name:'Kibble (Stego Egg)',qty:100},
  {id:343, name:'Kibble (Trike Egg)',qty:100},
  {id:344, name:'Kibble (Carbonemys Egg)',qty:100},
  {id:345, name:'Ankylo Egg',qty:1},
  {id:346, name:'Argentavis Egg',qty:1},
  {id:347, name:'Titanaboa Egg',qty:1},
  {id:348, name:'Carno Egg',qty:1},
  {id:349, name:'Dilo Egg',qty:1},
  {id:350, name:'Pteranadon Egg',qty:1},
  {id:351, name:'Sarco Egg',qty:1},
  {id:352, name:'Polminoscorpius Egg',qty:1},
  {id:353, name:'Araneo Egg',qty:1},
  {id:354, name:'Spino Egg',qty:1},
  {id:355, name:'Turtle Egg',qty:1},
  {id:356, name:'Rockwell Recipes: Egg-based Kibble',qty:1},
  {id:357, name:'Reinforced Window',qty:1},
  {id:358, name:'Reinforced Trap Door',qty:1},
  {id:359, name:'Omni Directional Lamp Post',qty:2},
  {id:360, name:'Industrial Grill',qty:1},
  {id:361, name:'Pumpaction Shotgun',qty:1},
  {id:362, name:'Crossbow (Stone Arrow)',qty:100},
  {id:363, name:'Forrest Coloring',qty:1},
  {id:364, name:'Parchement Coloring',qty:1},
  {id:365, name:'Pink Coloring',qty:1},
  {id:366, name:'Royalty Coloring',qty:1},
  {id:367, name:'Silver Coloring',qty:1},
  {id:368, name:'Sky Coloring',qty:1},
  {id:369, name:'Tan Coloring',qty:1},
  {id:370, name:'Tangerine Coloring',qty:1},
  {id:371, name:'Rockwell Recipes: Decorative Coloring',qty:1},
  {id:372, name:'Transponder Tracker',qty:1},
  {id:373, name:'Transponder Node',qty:1},
  {id:374, name:'Single Panel Flag',qty:1},
  {id:375, name:'Feeding Trough',qty:1},
  {id:376, name:'Compound Bow (Metal Arrows)',qty:1},
  {id:377, name:'Metal Arrow',qty:100},
  {id:378, name:'Canteen (Empty)',qty:8},
  {id:379, name:'Canteen (Filled)',qty:8},
  {id:380, name:'Metal Sickle',qty:1},
  {id:381, name:'Behemoth Stone Dino Gateway',qty:1},
  {id:382, name:'Behemoth Reinforced Dino Gate',qty:1},
  {id:383, name:'Bear Trap',qty:1},
  {id:384, name:'Large Bear Trap',qty:1},
  {id:385, name:'Trike Bone Helmet Skin',qty:1},
  {id:386, name:'Re-Fertilizer',qty:10},
  {id:387, name:'Scuba Tank',qty:1},
  {id:388, name:'Scuba Mask',qty:1},
  {id:389, name:'Scuba Flippers',qty:1},
  {id:390, name:'Plant Species X Seed',qty:2},
  {id:391, name:'Plant Species X Seed',qty:2},
  {id:392, name:'Spray Painter',qty:1},
  {id:393, name:'Doedicurus Saddle',qty:1},
  {id:394, name:'Roof',qty:10},
  {id:395, name:'Sloped Thatch Wall Left',qty:2},
  {id:396, name:'Sloped Thatch Wall Right',qty:2},
  {id:397, name:'Wooden Roof',qty:10},
  {id:398, name:'Sloped Wood Wall Left',qty:2},
  {id:399, name:'Sloped Wood Wall Right',qty:2},
  {id:400, name:'Stone Roof',qty:10},
  {id:401, name:'Sloped Stone Wall Left',qty:2},
  {id:402, name:'Sloped Stone Wall Right',qty:2},
  {id:403, name:'Sloped Metal Roof',qty:10},
  {id:404, name:'Sloped Metal Wall Left',qty:2},
  {id:405, name:'Sloped Metal Wall Right',qty:2},
  {id:406, name:'Magenta Coloring',qty:1},
  {id:407, name:'Brick Coloring',qty:1},
  {id:408, name:'Cantaloupe Coloring',qty:1},
  {id:409, name:'Mud Coloring',qty:1},
  {id:410, name:'Navy Coloring',qty:1},
  {id:411, name:'Olive Coloring',qty:1},
  {id:412, name:'Slate Coloring',qty:1},
  {id:413, name:'Mindwipe Tonic',qty:1},
  {id:414, name:'Wooden Raft',qty:1},
  {id:415, name:'Bronto Platform Saddle',qty:1},
  {id:416, name:'Dune Buggy Vehicle Test',qty:1},
  {id:417, name:'Pachy Saddle',qty:1},
  {id:418, name:'Pachycephalosaurus Egg',qty:1},
  {id:419, name:'Kibble (Pachy Egg)',qty:100},
  {id:420, name:'Rockwell Recipes- Mindwipe Tonic',qty:1},
  {id:421, name:'Painting Canvas',qty:1},
  {id:422, name:'Paracer Saddle',qty:1},
  {id:423, name:'Paracer Platform Saddle',qty:1},
  {id:424, name:'Pelt',qty:1},
  {id:425, name:'Dimorphodon Egg',qty:1},
  {id:426, name:'Kibble (Dimorphodon Egg)',qty:1},
  {id:427, name:'Beelzebufo Saddle',qty:1},
  {id:428, name:'Megaloceros Saddle',qty:1},
  {id:429, name:'Fur Leggings',qty:1},
  {id:430, name:'Fur Chestpiece',qty:1},
  {id:431, name:'Fur Cap',qty:1},
  {id:432, name:'Fur Boots',qty:1},
  {id:433, name:'Fur Gauntlets',qty:1},
  {id:434, name:'Wooden Club',qty:1},
  {id:435, name:'Poison Grenade',qty:5},
  {id:436, name:'Fabricated Sniper Rifle',qty:1},
  {id:437, name:'DodoRex Mask Skin',qty:1},
  {id:438, name:'Greenhouse Wall',qty:10},
  {id:439, name:'Greenhouse Ceiling',qty:10},
  {id:440, name:'Greenhouse DoorFrame',qty:1},
  {id:441, name:'Greenhouse Door',qty:1},
  {id:442, name:'Sloped Greenhouse wall Left',qty:2},
  {id:443, name:'Sloped Greenhouse wall Right',qty:2},
  {id:444, name:'Sloped Greenhouse Roof',qty:8},
  {id:445, name:'Greenhouse Window',qty:1},
  {id:446, name:'Riot Leggings',qty:1},
  {id:447, name:'Riot Chestpiece',qty:1},
  {id:448, name:'Riot Gauntlets',qty:1},
  {id:449, name:'Riot Boots',qty:1},
  {id:450, name:'Riot Helmet',qty:1},
  {id:451, name:'Electric Prod',qty:1},

  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedSniperBullet.PrimalItemAmmo_AdvancedSniperBullet'",name:"Advanced Sniper Bullet",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_AlphaRex.PrimalItemTrophy_AlphaRex'",name:"Alpha Rex Trophy",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AnglerGel.PrimalItemResource_AnglerGel'",name:"Angler Gel",qty:100},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SpiderSaddle.PrimalItemArmor_SpiderSaddle'",name:"Araneo Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TurretBallista.PrimalItemStructure_TurretBallista'",name:"Ballista",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_BallistaArrow.PrimalItemAmmo_BallistaArrow'",name:"Ballista Arrow",qty:100},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_Shield.PrimalItemArmor_Shield'",name:"Base Shield",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_BeerBarrel.PrimalItemStructure_BeerBarrel'",name:"Beer Barrel",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BeerJar.PrimalItemConsumable_BeerJar'",name:"Beer Jar",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BeerJarAlt.PrimalItemConsumable_BeerJarAlt'",name:"Beer Jar (alt)",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneSauro.PrimalItemCostume_BoneSauro'",name:"Bone Bronto Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_Boulder.PrimalItemAmmo_Boulder'",name:"Boulder",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/Vday/PrimalItemConsumable_ValentinesChocolate.PrimalItemConsumable_ValentinesChocolate'",name:"Box o' Chocolates",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Broodmother.PrimalItemTrophy_Broodmother'",name:"Broodmother Trophy",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BugRepellant.PrimalItemConsumable_BugRepellant'",name:"Bug Repellant",qty:2},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_Bed_Modern.PrimalItemStructure_Bed_Modern'",name:"Bunk Bed",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_CandyClub.PrimalItemSkin_CandyClub'",name:"Candy Cane Club Skin",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TurretCatapult.PrimalItemStructure_TurretCatapult'",name:"Catapult Turret",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TurkeyHat.PrimalItemSkin_TurkeyHat'",name:"Chieftan Hat Skin",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Coal.PrimalItemResource_Coal'",name:"Coal",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DinoSantaHat.PrimalItemSkin_DinoSantaHat'",name:"Dino Santa Hat Skin",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/BuildingBases/PrimalItemStructure_ElevatorTrackBase.PrimalItemStructure_ElevatorTrackBase'",name:"Elevator Track Base",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_GalliEgg.PrimalItemConsumable_Kibble_GalliEgg'",name:"Gallimimus Kibble",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieGloves.PrimalItemArmor_GhillieGloves'",name:"Ghillie Gloves",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieHelmet.PrimalItemArmor_GhillieHelmet'",name:"Ghillie Helmet",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhilliePants.PrimalItemArmor_GhilliePants'",name:"Ghillie Pants",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieShirt.PrimalItemArmor_GhillieShirt'",name:"Ghillie Shirt",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Christmas/PrimalItemStructure_StorageBox_ChristmasGift.PrimalItemStructure_StorageBox_ChristmasGift'",name:"Gift Box",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Gigant.PrimalItemConsumable_Egg_Gigant'",name:"Giganotosaurus Egg",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_GigantSaddle.PrimalItemArmor_GigantSaddle'",name:"Giganotosaurus Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieBoots.PrimalItemArmor_GhillieBoots'",name:"Gille Boots",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_GrapplingHook.PrimalItemAmmo_GrapplingHook'",name:"Grappling Hook",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_Furniture_Gravestone.PrimalItemStructure_Furniture_Gravestone'",name:"Gravestone",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Christmas/PrimalItemStructure_XmasLights.PrimalItemStructure_XmasLights'",name:"Holiday Lights",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Christmas/PrimalItemStructure_Stocking.PrimalItemStructure_Stocking'",name:"Holiday Stocking",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Christmas/PrimalItemStructure_ChristmasTree.PrimalItemStructure_ChristmasTree'",name:"Holiday Tree",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_SeaMine.PrimalItemStructure_SeaMine'",name:"Homing Underwater Mine",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_IndustrialCookingPot.PrimalItemStructure_IndustrialCookingPot'",name:"Industrial CookingPot",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_IndustrialForge.PrimalItemStructure_IndustrialForge'",name:"Industrial Forge",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TrophyBase.PrimalItemStructure_TrophyBase'",name:"Interim Trophy Base",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_KairukuEgg.PrimalItemConsumable_Kibble_KairukuEgg'",name:"Kibble (Kairuku Egg)",qty:100},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_QuetzEgg.PrimalItemConsumable_Kibble_QuetzEgg'",name:"Kibble (Quetz Eggs)",qty:100},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/BuildingBases/PrimalItemStructure_ElevatorPlatformLarge.PrimalItemStructure_ElevatorPlatformLarge'",name:"Large Elevator Platform",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/Test/PrimalItem_WeaponMagnifyingGlass.PrimalItem_WeaponMagnifyingGlass'",name:"Magnifying Glass",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/BuildingBases/PrimalItemStructure_ElevatorPlatfromMedium.PrimalItemStructure_ElevatorPlatfromMedium'",name:"Medium Elevator Platform",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_ReindeerStag.PrimalItemCostume_ReindeerStag'",name:"Megaloceros Reindeer Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_ReindeerStag.PrimalItemCostume_ReindeerStag'",name:"Megaloceros Reindeer Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Metal/PrimalItemStructure_MetalRailing.PrimalItemStructure_MetalRailing'",name:"Metal Railing",qty:10},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_MetalShield.PrimalItemArmor_MetalShield'",name:"Metal Shield",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSword.PrimalItem_WeaponSword'",name:"Metal Sword",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TurretMinigun.PrimalItemStructure_TurretMinigun'",name:"Minigun Turret",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_MistleToe.PrimalItemResource_MistleToe'",name:"Mistletoe",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle_Platform.PrimalItemArmor_MosaSaddle_Platform'",name:"Mosasaurus Platform",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle.PrimalItemArmor_MosaSaddle'",name:"Mosasaurus Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Polymer_Organic.PrimalItemResource_Polymer_Organic'",name:"Organic Polymer",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Oviraptor.PrimalItemConsumable_Egg_Oviraptor'",name:"Oviraptor Egg",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PlesiSaddle_Platform.PrimalItemArmor_PlesiSaddle_Platform'",name:"Plesiosaur Platform Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ProcoptodonSaddle.PrimalItemArmor_ProcoptodonSaddle'",name:"Procoptodon Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Quetz.PrimalItemConsumable_Egg_Quetz'",name:"Quetz Egg",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_QuetzSaddle_Platform.PrimalItemArmor_QuetzSaddle_Platform'",name:"Quetz Platform Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_QuetzSaddle_Platform.PrimalItemArmor_QuetzSaddle_Platform'",name:"Quetz Saddle Platform",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_TransparentRiotShield.PrimalItemArmor_TransparentRiotShield'",name:"Riot Shield",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TurretRocket.PrimalItemStructure_TurretRocket'",name:"Rocket Turret",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SantaHat.PrimalItemSkin_SantaHat'",name:"Santa Hat Skin",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_ScubaPants.PrimalItemArmor_ScubaPants'",name:"Scuba Leggings",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/BuildingBases/PrimalItemStructure_ElevatorPlatformSmall.PrimalItemStructure_ElevatorPlatformSmall'",name:"Small Elevator Platform",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_GasGrenade.PrimalItem_GasGrenade'",name:"Smoke Grenade",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Christmas/PrimalItemStructure_Snowman.PrimalItemStructure_Snowman'",name:"Snowman",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumableSoap.PrimalItemConsumableSoap'",name:"Soap",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Stone/PrimalItemStructure_StoneRailing.PrimalItemStructure_StoneRailing'",name:"Stone Railing",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_SotF_1st.PrimalItemTrophy_SotF_1st'",name:"Survival of the Fittest Trophy: 1st Place",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_SotF_2nd.PrimalItemTrophy_SotF_2nd'",name:"Survival of the Fittest Trophy: 2nd Place",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_SotF_3rd.PrimalItemTrophy_SotF_3rd'",name:"Survival of the Fittest Trophy: 3rd Place",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_SotFUS_1st.PrimalItemTrophy_SotFUS_1st'",name:"Survival of the Fittest: Unnatural Selection Trophy: 1st Place",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_SotFUS_2nd.PrimalItemTrophy_SotFUS_2nd'",name:"Survival of the Fittest: Unnatural Selection Trophy: 2nd Place",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_SotFUS_3rd.PrimalItemTrophy_SotFUS_3rd'",name:"Survival of the Fittest: Unnatural Selection Trophy: 3rd Place",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TerrorBirdSaddle.PrimalItemArmor_TerrorBIrdSaddle'",name:"TerrorBird Saddle",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TopHat.PrimalItemSkin_TopHat'",name:"Top Hat Skin",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_TranqDart.PrimalItemAmmo_TranqDart'",name:"Tranq Dart",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TrophyBase.PrimalItemStructure_TrophyBase'",name:"Trophy Base",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_WallTorch.PrimalItemStructure_WallTorch'",name:"Wall Torch",qty:10},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_WarMap.PrimalItemStructure_WarMap'",name:"War Map",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_Wardrums.PrimalItemStructure_Wardrums'",name:"Wardrums",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wishbone.PrimalItemResource_Wishbone'",name:"Wishbone",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_Furniture_WoodBench.PrimalItemStructure_Furniture_WoodBench'",name:"Wood Bench",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_Furniture_WoodChair.PrimalItemStructure_Furniture_WoodChair'",name:"Wood Chair",qty:2},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_WoodCage.PrimalItemStructure_WoodCage'",name:"Wooden Cage",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_WoodRailing.PrimalItemStructure_WoodRailing'",name:"Wooden Railing",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_WoodShield.PrimalItemArmor_WoodShield'",name:"Wooden Shield",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Wooden/PrimalItemStructure_Furniture_WoodTable.PrimalItemStructure_Furniture_WoodTable'",name:"Wooden Table",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Christmas/PrimalItemStructure_Wreath.PrimalItemStructure_Wreath'",name:"Wreath",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneCarno.PrimalItemCostume_BoneCarno'",name:"Bone Carno Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneRaptor.PrimalItemCostume_BoneRaptor'",name:"Bone Raptor Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneRex.PrimalItemCostume_BoneRex'",name:"Bone Rex Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneSauro.PrimalItemCostume_BoneSauro'",name:"Bone Sauro Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneStego.PrimalItemCostume_BoneStego'",name:"Bone Stego Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneTrike.PrimalItemCostume_BoneTrike'",name:"Bone Trike Costume",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodorexMask.PrimalItemSkin_DodorexMask'",name:"DodoRex Mask",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Halloween/PrimalItemStructure_Pumpkin.PrimalItemStructure_Pumpkin'",name:"Pumpkin",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Halloween/PrimalItemStructure_Scarecrow.PrimalItemStructure_Scarecrow'",name:"Scarecrow",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Halloween/PrimalItemStructure_HW_Grave.PrimalItemStructure_HW_Grave'",name:"Tomb/Grave Stone",qty:1},
  {id:"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WitchHat.PrimalItemSkin_WitchHat'",name:"Witch Hat",qty:1}
].map( (item,i) => { item.index = i; return item;});};